---
- name: Create KeyPair for Openstack
  hosts: localhost
  connection: local

  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

  tasks:

    - debug :
        msg: "{{ config_file }}"

    - stat:
        path: "{{ config_file }}"
      register: st

    - include_vars:
        "{{ config_file }}"
      when: st.stat.exists and st.stat.isreg

    - debug:
        msg: "{{ clouds }}’"

    - name: Generate key files
      user:
        name: "{{ ansible_env.USER }}"
        generate_ssh_key: yes
        ssh_key_file: .ssh/test_id_rsa

    - name: Ensure Keypair is present
      os_keypair:
        name: keypair1
        state: present
        cloud: "{{ clouds }}"
        public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
