---
- name: Create KeyPair for Openstack
  hosts: localhost
  connection: local

  tasks:

    - name: Generate key files
      user:
        name: "{{ ansible_env.USER }}"
        generate_ssh_key: yes
        ssh_key_file: ".ssh/{{ keypair_name }}_id_rsa"

    - name: Add Generated Key to Ansible Tower Credentials
      tower_credential:
        name: "{{ keypair_name }}"
        kind: ssh
        organization: Ansible Demo
        ssh_key_data: ".ssh/{{ keypair_name }}_id_rsa"
        username: cloud-user
        become_method: sudo
        become_username: root
        state: present

    - name: Ensure Keypair is present
      os_keypair:
        name: "{{ keypair_name }}"
        state: present
        cloud: "{{ cloud_name }}"
        public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
