---
- name: Create KeyPair for Openstack
  hosts: localhost
  connection: local

  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

  tasks:

    - debug :
        var: config_file

    - name: Generate key files
      user:
        name: "{{ ansible_env.USER }}"
        generate_ssh_key: yes
        ssh_key_file: .ssh/test_id_rsa

    - name: Ensure Keypair is present
      os_keypair:
        name: keypair1
        state: present
        cloud: "{{ clouds }}"
        public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
