---
- name: Create KeyPair for Openstack
  hosts: localhost
  connection: local

  vars:
    cloud_name: "{{ lookup('env', 'OS_CLOUD') }}"

  tasks:

    - debug :
        var: "{{ cloud_name }}"

    - name: Generate key files
      user:
        name: "{{ ansible_env.USER }}"
        generate_ssh_key: yes
        ssh_key_file: .ssh/test_id_rsa

    - name: Ensure Keyair is present
      os_keypair:
        name: keypair1
        auth_type:
        state: present
        cloud: "{{ cloud_name }}"
        public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
