---
- name: Create KeyPair for Openstack
  hosts: localhost
  connection: local

  tasks:

    - name: Generate key files
      user:
        name: ansible
        generate_ssh_key: yes
        ssh_key_file: .ssh/test_id_rsa

    - name: Ensure Keypair is present
      os_keypair:
        name: "{{ keypair_name }}"
        state: present
        cloud: "{{ cloud_name }}"
        public_key_file: /home/ansible/.ssh/ansible_id_rsa.pub"
