---
- name: Ensure Public Subnet Network is present
  os_subnet:
    name: public
    state: present
    network_name: pubnetwork1
    cidr: 10.10.10.0/24
    host_routes:
      - destination: 0.0.0.0/24
        nexthop: 10.10.10.0
      - destination: 192.168.0.0/24
        nexthop: 192.168.0.0
    dns_nameservers:
      - 8.8.8.7
      - 8.8.8.8
    cloud: ospcloud
