---

- name: Process [ instance ]
  import_tasks: "instance/instance.yml"
  vars:
    instance: "{{ cloud_compute_instance_dict.value }}"
  with_dict: "{{ cloud_compute.instance | default({}) }}"
  loop_control:
    loop_Var: cloud_compute_instance_dict
    label: "{{ cloud_compute_instance_dict.key }}"
  when: cloud_compute.instance is mapping
