---
# tasks file for osp_keypair
- name: Generate key files
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    home: "{{ os_keypair_path }}"
    ssh_key_file: "{{ keypair_path }}/{{ keypair_name }}_id_rsa"

- name: Ensure Keyair is present
  os_keypair:
    name: "{{ os_keypair_name }}"
    state: present
    cloud: "{{ os_cloud_name }}"
    public_key_file: "{{ os_keypair_path }}/{{ os_keypair_name }}_id_rsa.pub"
