---
- name: Install Tomcat packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tomcat

- name: Enable Tomcat at boot
  service:
    name: tomcat
    state: started
    enabled: yes

- name: Ensure Firewalld service is up and running
  service:
    name: firewalld
    state: started

- name: Ensure Firewall port is open for Tomcat
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify:
    - restart tomcat
