---
- name: Install necessary packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - haproxy

- name: Enable haproxy at boot
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Copy HA Proxy config file
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
